version: '3'

services:
  web:
    image: botfrombot
    container_name: cherrypy_container
    build: .
    ports:
      - 8080:8080
    command: python app.py 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true